"""make_firdatasource_metadata_columns_nullable

Revision ID: 0e3aaec3cbcb
Revises: 
Create Date: 2026-03-31 23:22:30.928502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3aaec3cbcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firdatasource', 'last_updated',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('firdatasource', 'date_posted',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('firdatasource', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firdatasource', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('firdatasource', 'date_posted',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('firdatasource', 'last_updated',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
